enabled: false
mongodb: "mongodb://localhost:27017"
db-name: "serverlogs"
server-name: ""
timer: 15
loggers:
  chat: true
  consolecommand: true
  playercommand: true
  playerjoin: true
  playerquit: true
consolecommand-ignore:
  - list
  - save-on
  - save-all
