enabled: false
mongodb: "mongodb://localhost:27017"
db-name: "serverlogs"
server-name: ""
timer: 15
loggers:
  chat: true
  consolecommand: true
  onlineplayers: true
  playerblockbreak: true
  playerblockplace: true
  playercommand: true
  playerdamageentity: true
  playerdeath: true
  playerjoin: true
  playerkillplayer: true
  playerquit: true
consolecommand-ignore:
  - list
  - save-on
  - save-all
  - save-off
onlineplayers-interval: 10
