name: Build and Deploy Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: ServerLogger
        # A file, directory or wildcard pattern that describes what to upload
        path: target/ServerLogger.jar
        # The desired behavior if no files are found using the provided path (warn/error/ignore)
        if-no-files-found: warn

    - name: Release artifact
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: latest
        draft: true
        prerelease: true
        title: "ServerLogger"
        files: "target/ServerLogger.jar"
